### ISSUE TITLE
gconf2 dependecies missing for .deb package

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/snapshot-slider#16]
On Lubuntu 16.10, this installs the missing dependency:
```
sudo apt-get install gconf2 gconf-service libgconf-2-4 gconf-service-backend gconf2-common
```

**Comment by porst17** [comment]
The `.deb` actually *lists* the correct dependencies [by default](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions), but they are *not installed by default* on post Ubuntu 15.10 systems.

This can be fixed via
```
sudo dpkg -i snapshot-slider_X.x.x_amd4.deb # install the package even though it misses dependencies
sudo apt-get install -f                     # install missing dependencies (-f = fix missing)
```
With apt 1.1 (Ubuntu 16.04+), this can also be done in one step
```
sudo apt install snapshot-slider_X.x.x_amd4.deb
```

**Comment by malex984** [comment]
@porst17 Note that you need to give specify a path to the local `.deb` file (at least for `apt install`)

**Comment by porst17** [comment]
Of course. Also `X.x.x` must be replaced by the actual version.
