### ISSUE TITLE
Outdated list of Snapshots in `defaults.json`

### ISSUE THREAD

**Issue by malex984** [IMAGINARY/snapshot-slider#25]
According too https://imaginary.org/api/snapshots.json there are currently 61 Snapshots on the site, but
only 41 older snapshots are listed in https://github.com/IMAGINARY/snapshot-slider/blob/master/defaults.json (and a single front page). 

AFAICS that `defaults.json` is being used as `.config/SNAPSHOT slider/Settings` 
by freshly installed SNAPSHOT Slider by default. Thus it only gets 42 Snapshots without auto-update via `u`...

**Comment by malex984** [comment]
I would suggest to remove that list of articles from `defaults.json` in favor of a single autoUpdate.url via Imaginary site API!

**Comment by porst17** [comment]
This would mean that the user would need to trigger the update on the first run or that the SNAPSHOT slider would need to do it by itself. How should the whole process should look like from start to end, also with respect to online and offline installation?

**Comment by malex984** [comment]
IMO the list of articles does not belong to `.config/SNAPSHOT slider/Settings` rather i would suggest to keep a current `snapshots.json` in `.cache/SNAPSHOT slider/` (for later update checking, see below).

Since SNAPSHOT slider installer does not contain PDFs - there is no point in having and installing a default list of articles (i.e. `snapshots.json`). 

* If `snapshots.json` is absent at the start of Slider run - it should fail if offline, otherwise try to do update: 
  1. get https://imaginary.org/api/snapshots.json (and fail/warn if not possible), 
  2. download all PDFs according to it into the local cache (and fail/warn if not possible), 
  3. cache that `snapshots.json` locally. 

* If `snapshots.json` is present (and valid) at the start of Slider run - check the snapshots listed in it w.r.t. the local cache and process/display them (no matter offline or online). 

* In case of update (`u`): 
  1. get https://imaginary.org/api/snapshots.json (and stop/warn if not possible), 
  2. compare with the local one (if present) to get a diff,
  3. download new PDFs according to the diff (and stop/warn if not possible), 
  4. cache new `snapshots.json` locally and remove outdated PDFs (according to the diff) and corresponding PNGs.
  5. refresh current view according to the diff

Note: there may be a separate setting/flag in `.config/SNAPSHOT slider/Settings` to specify what to do on start, e.g. to try auto-update on each start etc...

How does this sound?

**Comment by porst17** [comment]
The reason why the list of snapshots is part of the config is due to the rush it was developed in. There was simply no time to think about such design decisions.

I agree, this kind of data should be put into a separate `snapshots.json` file.

**Comment by porst17** [comment]
I implemented what you suggested. I tested a bit, but not thoroughly.
